import type { AppTheme } from './types';

/**
 * 将主题 token 映射为 CSS 变量。
 *
 * 这是 token → CSS 变量名的唯一映射来源：
 * - 运行时由 `ThemeContext` 注入到 `:root`。
 * - 构建时由 `scripts/build-tokens-css.mjs` 生成静态的 `design-tokens.css`（供非 React 项目复用）。
 *
 * 本文件只允许 `import type`，以便构建脚本用 Node 的类型擦除直接导入。
 */
export function themeToCssVariables(theme: AppTheme): Record<string, string> {
  const { tokens } = theme;

  return {
    '--bg-primary': tokens.background.primary,
    '--bg-secondary': tokens.background.secondary,
    '--bg-card': tokens.background.card,
    '--bg-card-hover': tokens.background.cardHover,
    '--bg-selected': tokens.background.selected,
    '--bg-control': tokens.background.control,
    '--border-divider': tokens.border.divider,
    '--text-strong': tokens.text.strong,
    '--text-regular': tokens.text.regular,
    '--text-secondary': tokens.text.secondary,
    '--text-decorative': tokens.text.decorative,
    '--text-disabled': tokens.text.disabled,
    '--text-inverse': tokens.text.inverse,
    '--highlight': tokens.brand.primary,
    '--highlight-hover': tokens.brand.hover,
    '--highlight-active': tokens.brand.active,
    '--highlight-foreground': tokens.brand.foreground,
    '--highlight-light': tokens.brand.light,
    '--highlight-rgb': tokens.brand.rgb,
    '--color-notification-badge': tokens.notification.badge,
    '--color-indicator-up': tokens.indicator.up,
    '--color-indicator-down': tokens.indicator.down,
    '--color-risk-high': tokens.risk.high,
    '--color-risk-medium': tokens.risk.medium,
    '--color-risk-low': tokens.risk.low,
    '--color-success': tokens.status.success,
    '--color-warning': tokens.status.warning,
    '--color-danger': tokens.status.danger,
    '--color-info': tokens.status.info,
    '--color-sentiment-positive': tokens.sentiment.positive,
    '--color-sentiment-neutral': tokens.sentiment.neutral,
    '--color-sentiment-negative': tokens.sentiment.negative,
    '--color-chart-1': tokens.chart[0],
    '--color-chart-2': tokens.chart[1],
    '--color-chart-3': tokens.chart[2],
    '--color-chart-4': tokens.chart[3],
    '--color-chart-5': tokens.chart[4],
    '--color-chart-6': tokens.chart[5],
    '--color-chart-7': tokens.chart[6],
    '--color-chart-8': tokens.chart[7],
    '--color-chart-9': tokens.chart[8],
    '--color-chart-10': tokens.chart[9],
    '--color-chart-11': tokens.chart[10],
    '--font-sans': tokens.typography.fontSans,
    '--font-display': tokens.typography.fontDisplay,
    '--font-data': tokens.typography.fontData,
    '--font-size-body': tokens.typography.bodyFontSize,
    '--line-height-body': tokens.typography.bodyLineHeight,
    '--radius-xs': tokens.radius.xs,
    '--radius-sm': tokens.radius.sm,
    '--radius-md': tokens.radius.md,
    '--radius-lg': tokens.radius.lg,
    '--radius-xl': tokens.radius.xl,
    '--radius-full': tokens.radius.full,
    '--radius': tokens.radius.md,
    '--space-xxs': tokens.spacing.xxs,
    '--space-xs': tokens.spacing.xs,
    '--space-sm': tokens.spacing.sm,
    '--space-md': tokens.spacing.md,
    '--space-base': tokens.spacing.base,
    '--space-lg': tokens.spacing.lg,
    '--space-xl': tokens.spacing.xl,
    '--space-xxl': tokens.spacing.xxl,
    '--space-section': tokens.spacing.section,
    '--layout-page-x': tokens.spacing.pageX,
    '--component-card-padding': tokens.component.card.padding,
    '--shadow-none': tokens.shadow.none,
    '--shadow-card': tokens.shadow.card,
    '--shadow-card-hover': tokens.shadow.cardHover,
    '--shadow-popover': tokens.shadow.popover,
    '--shadow-modal': tokens.shadow.modal,
    '--overlay-scrim': tokens.overlay.scrim,
    '--link-default': tokens.link.default,
    '--link-hover': tokens.link.hover,
    '--link-muted': tokens.link.muted,
    '--link-legal': tokens.link.legal,
    '--accent-one': tokens.accent.one,
    '--accent-two': tokens.accent.two,
    '--accent-premium': tokens.accent.premium,
    '--accent-standard': tokens.accent.standard,
    '--component-button-radius': tokens.component.button.radius,
    '--component-button-height': tokens.component.button.height,
    '--component-button-padding-x': tokens.component.button.paddingX,
    '--component-card-radius': tokens.component.card.radius,
    '--component-card-shadow': tokens.component.card.shadow,
    '--component-card-hover-shadow': tokens.component.card.hoverShadow,
    '--component-input-radius': tokens.component.input.radius,
    '--component-input-height': tokens.component.input.height,
    '--component-popover-radius': tokens.component.popover.radius,
    '--component-popover-padding': tokens.component.popover.padding,
    '--component-popover-shadow': tokens.component.popover.shadow,
    '--component-modal-radius': tokens.component.modal.radius,
    '--component-modal-shadow': tokens.component.modal.shadow,
    '--sidebar-bg': tokens.background.card,
    '--sidebar-border': tokens.border.divider,
    '--sidebar-text-strong': tokens.text.strong,
    '--sidebar-text-regular': tokens.text.regular,
    '--sidebar-text-secondary': tokens.text.secondary,
    '--sidebar-text-disabled': tokens.text.disabled,
    '--sidebar-hover-bg': tokens.background.secondary,
    '--sidebar-tag-bg': tokens.background.secondary,
    '--background': tokens.shadcn.background,
    '--foreground': tokens.shadcn.foreground,
    '--card': tokens.shadcn.card,
    '--card-foreground': tokens.shadcn.cardForeground,
    '--popover': tokens.shadcn.popover,
    '--popover-foreground': tokens.shadcn.popoverForeground,
    '--primary': tokens.shadcn.primary,
    '--primary-foreground': tokens.shadcn.primaryForeground,
    '--secondary': tokens.shadcn.secondary,
    '--secondary-foreground': tokens.shadcn.secondaryForeground,
    '--muted': tokens.shadcn.muted,
    '--muted-foreground': tokens.shadcn.mutedForeground,
    '--accent': tokens.shadcn.accent,
    '--accent-foreground': tokens.shadcn.accentForeground,
    '--destructive': tokens.shadcn.destructive,
    '--destructive-foreground': tokens.shadcn.destructiveForeground,
    '--border': tokens.shadcn.border,
    '--input': tokens.shadcn.input,
    '--ring': tokens.shadcn.ring,
  };
}
